# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\ntest.proto\",\n\x04TUid\x12\x0b\n\x03Uid\x18\x01 \x01(\t\x12\x17\n\x0f\x41ssociatedItems\x18\x02 \x03(\t')
)




_TUID = _descriptor.Descriptor(
  name='TUid',
  full_name='TUid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Uid', full_name='TUid.Uid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AssociatedItems', full_name='TUid.AssociatedItems', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=58,
)

DESCRIPTOR.message_types_by_name['TUid'] = _TUID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TUid = _reflection.GeneratedProtocolMessageType('TUid', (_message.Message,), {
  'DESCRIPTOR' : _TUID,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:TUid)
  })
_sym_db.RegisterMessage(TUid)


# @@protoc_insertion_point(module_scope)
